### ISSUE TITLE
Vtancer script not loading

### ISSUE THREAD

**Issue by Vincent0366** [E66666666/GTAVStancer#1]
Hi, im new to this platform so im sorry if im not posting this in the correct place. I have been having issues with Vstancer for the past 3 months. It doesn't load. The menu just wont show up. I have tried to reinstall it, and reinstall my game and i just dont understand why it wont work. Anyone here able to help me? I'll attach the log, but it isnt to very much help i dont think. The reason the log is so short is because i reinstalled vstancer.

Log: 
[10:49:34.633] [ INFO] VStancer v0.2.4
[10:49:34.637] [ INFO] Game version 56
[10:49:34.640] [ INFO] Script registered
[10:51:09.940] [ INFO] Script started
[10:51:10.477] [ INFO] Settings read
[10:51:10.481] [ INFO] Initialization finished

**Comment by E66666666** [comment]
Well, it's loading, so that's something.

Depending on your keyboard locale the default keys might be somewhere else. You can edit settings_menu.ini to reassign keys or use the cheat code in there to open the menu.

**Comment by Vincent0366** [comment]
> Well, it's loading, so that's something.
> 
> Depending on your keyboard locale the default keys might be somewhere else. You can edit settings_menu.ini to reassign keys or use the cheat code in there to open the menu.

I have tried to use the cheat code to open it, but that doesn't work either. So its something wrong with the script or something

**Comment by E66666666** [comment]
The script works fine if it shows logging.

You can still assign it to some other hotkey more convenient for you. Try an `F_` key like F8.

**Comment by Vincent0366** [comment]
> The script works fine if it shows logging.
> 
> You can still assign it to some other hotkey more convenient for you. Try an `F_` key like F8.

Thanks, ill try and report back

**Comment by Vincent0366** [comment]
I dont know hwat was wrong but it worked to change the key. Well i appreciate it, and i feel really dumb haha
